esko/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('esko_app/', include('esko_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

esko_app/urls.py
from django.urls import path, include

from .views import (PostListView, PostDetailView,PostCreateView, PostUpdateView, 
	PostDeleteView, AddCommentView, HomeListView, PasswordsChangeView, 
	TagIndexView, ReportView, ReportDeleteView, ReportPostDeleteView)

from . import views

from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'esko_app'
urlpatterns = [
	path('', views.index, name='index'),
	path('signup/', views.signup, name='signup'),
	path('login/', views.loginPage, name='login'),

	path('home/', views.home, name='home'),
	path('profile/', views.profile, name='profile'),

	path('category/', views.category, name='category'),
	path('search_tags/', views.search_tags, name='search_tags'),
	# path('sell/', views.sell, name='sell'),

	path('profileOther/<username>/', views.profileOther, name='profile-other'),
	path('profileOtherComment/<username>/', views.profileOtherComment, name='profile-other-comment'),

	path('postCategory/', views.PostByCategory, name='post_by_category'),
	path('searchTag/', views.SearchByTag, name='search_by_tags'),

	path('reported-posts/', views.reportedPosts, name='reported-posts'),
	path('post/<int:pk>/report', ReportView.as_view(), name='report-post'),
	path('report/<int:pk>/delete/', ReportDeleteView.as_view(), name='report-delete'),
	path('rpost/<int:pk>/delete/', ReportPostDeleteView.as_view(), name='rpost-delete'),


	# path('home/', HomeListView.as_view(), name='home'),
	# path('profile/', PostListView.as_view(), name='profile'),
	path('about/', views.about, name='about'),
	path('logout/', views.logoutUser, name='logout'),

	path('password-reset/', 
		PasswordsChangeView.as_view(template_name='esko_app/password_reset.html'),
		name= 'password_reset'),	
	path('password-reset/done/', views.password_success, name= 'password_success'),
	
	
	path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
	path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
	path('post/new/', PostCreateView.as_view(), name='post-create'),
	path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
	path('profileSettings/', views.profileSettings, name='profileSettings'),
	path('like/<int:pk>/',views.LikeView, name='like_post'),
	# path('likeHome/',views.LikeViewHome, name='like_post_home'),
	path('post/<int:pk>/comment', AddCommentView.as_view(), name='add_comment'),

	path('tags/<slug:tag_slug>/', TagIndexView.as_view(), name='posts_by_tags'),
	
	# path('post/new/', views.post, name='post-create'),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path, include

from .views import (PostListView, PostDetailView,PostCreateView, PostUpdateView, 
	PostDeleteView, AddCommentView, HomeListView, PasswordsChangeView)

from . import views

from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'esko_app'
urlpatterns = [
	path('', views.index, name='index'),
	path('signup/', views.signup, name='signup'),
	path('login/', views.loginPage, name='login'),

	path('home/', views.home, name='home'),
	path('profile/', views.profile, name='profile'),


	# path('home/', HomeListView.as_view(), name='home'),
	# path('profile/', PostListView.as_view(), name='profile'),
	path('about/', views.about, name='about'),
	path('logout/', views.logoutUser, name='logout'),

	path('password-reset/', 
		PasswordsChangeView.as_view(template_name='esko_app/password_reset.html'),
		name= 'password_reset'),	
	path('password-reset/done/', views.password_success, name= 'password_success'),
	
	
	path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
	path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
	path('post/new/', PostCreateView.as_view(), name='post-create'),
	path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
	path('profileSettings/', views.profileSettings, name='profileSettings'),
	path('like/<int:pk>/',views.LikeView, name='like_post'),
	path('post/<int:pk>/comment', AddCommentView.as_view(), name='add_comment'),
	# path('post/<int:pk>/report', ReportView.as_view(), name='report'),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

esko_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse


from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import User, Post, Comment, Report
from .forms import CreateUserForm, UserUpdateForm, ProfileUpdateForm, CommentForm, CreatePostForm, ReportForm

from .filters import PostFilter
from django.core.paginator import Paginator

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from taggit.models import Tag



# from django.forms import modelformset_factory
# from .forms import ImageForm
# from .models import Images


# Create your views here.


#landing page
def index(request):
	return render(request, 'esko_app/index.html')

#sign-up page
def signup(request):

	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			print('yes')
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Account successfully created!')
			return redirect('/esko_app/login/')
			
	else:
		print('no')
		form = CreateUserForm()	
	return render(request, 'esko_app/signup.html', {'form': form})



def loginPage(request):

	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(request, username=username, password=password)

		if user is not None:
			# correct username and password login the user
			login(request, user)
			return redirect('/esko_app/home/')
		else:
			messages.error(request, 'Error wrong username/password')

	return render(request, 'esko_app/login.html')


def logoutUser(request):
	logout(request)
	return redirect('/esko_app/login/')

def about(request):
	return render(request, 'esko_app/about.html')


def category(request):
	return render(request, 'esko_app/category.html')

def search_tags(request):
	if request.method == "POST":
		searched = request.POST['searched']
		# tags = Tag.objects.filter()
		return render(request, 'esko_app/search_tags.html', {'searched':searched})
	else:
		return render(request, 'esko_app/search_tags.html', {})



class PostListView(ListView):
	model = Post
	template_name = 'esko_app/profile.html' # <app>/model_viewtype.html
	context_object_name = 'posts'
	ordering = ['-date']


class HomeListView(ListView):
	model = Post
	template_name = 'esko_app/home.html' # <app>/model_viewtype.html
	context_object_name = 'posts'
	ordering = ['-date']


# @login_required(login_url= '/esko_app/login/')
# def home(request):
# 	posts = Post.objects.all().order_by('-date')
# 	# images = Images.objects.all()

# 	for post in posts:

# 		total_likes = post.total_likes()

# 		liked = False
# 		if post.likes.filter(id=request.user.id).exists():
# 			liked = True

# 	filtered_posts = PostFilter(
# 		request.GET,
# 		queryset=posts
# 	)
	
# 	post_paginator = Paginator(filtered_posts.qs, 3)
# 	page_num = request.GET.get('page')
# 	page = post_paginator.get_page(page_num)

# 	context = {
# 		'count' : post_paginator.count,
# 		'page' : page,
# 		'total_likes': total_likes,
# 		'liked': liked,
# 		# 'images': images,
# 	}	
# 	return render(request, 'esko_app/home.html', context)



@login_required(login_url= '/esko_app/login/')
def home(request):
	posts = Post.objects.all().order_by('-date')
	


	for post in posts:

		total_likes = post.total_likes()
		tag_list = post.tag_list()
		# print(tag_list)

		liked = False
		if post.likes.filter(id=request.user.id).exists():
			liked = True

	filtered_posts = PostFilter(
		request.GET,
		queryset=posts
	)
	
	post_paginator = Paginator(filtered_posts.qs, 3)
	page_num = request.GET.get('page')
	page = post_paginator.get_page(page_num)

	context = {
		'count' : post_paginator.count,
		'page' : page,
		'total_likes': total_likes,
		'liked': liked,
		'tag_list': tag_list,
	}	
	return render(request, 'esko_app/home.html', context)

@login_required(login_url= '/esko_app/login/')
def PostByCategory(request):
	posts = Post.objects.all().order_by('-date')


	for post in posts:

		total_likes = post.total_likes()

		liked = False
		if post.likes.filter(id=request.user.id).exists():
			liked = True

	filtered_posts = PostFilter(
		request.GET,
		queryset=posts
	)
	
	post_paginator = Paginator(filtered_posts.qs, 3)
	page_num = request.GET.get('page')
	page = post_paginator.get_page(page_num)

	context = {
		'count' : post_paginator.count,
		'page' : page,
		'total_likes': total_likes,
		'liked': liked,
	}	
	# return render(request, 'esko_app/home.html', context)
	return render(request, 'esko_app/sell.html', context)


class TagIndexView(ListView):
	model = Post
	template_name = 'esko_app/tagView.html' # <app>/model_viewtype.html
	context_object_name = 'posts'
	ordering = ['-date']

	def get_queryset(self):
		return Post.objects.filter(tags__slug=self.kwargs.get('tag_slug'))



def SearchByTag(request):
 
	if request.method == 'GET': # If the form is submitted
		search_query = request.GET.get('search_box', None)
		posts = Post.objects.filter(tags__contains=str(search_query))

		total_likes = 0
		liked = False
		# tag_list = ['tags']
		for post in posts:

			total_likes = post.total_likes()
			# tag_list = post.tag_list()

			liked = False
			if post.likes.filter(id=request.user.id).exists():
				liked = True

		filtered_posts = PostFilter(
			request.GET,
			queryset=posts
		)
		
		post_paginator = Paginator(filtered_posts.qs, 3)
		page_num = request.GET.get('page')
		page = post_paginator.get_page(page_num)

		context = {
			'count' : post_paginator.count,
			'page' : page,
			'total_likes': total_likes,
			'liked': liked,
			'search_query': search_query,
			'tag_list' : post.tag_list(),

		}	
		return render(request, 'esko_app/search_tags.html', context)


@login_required(login_url= '/esko_app/login/')
def profile(request):
	posts = Post.objects.filter(author=request.user).order_by('-date')

	total_likes = 0
	liked = False
	for post in posts:
		total_likes = post.total_likes()
		tag_list = post.tag_list()

		liked = False
		if post.likes.filter(id=request.user.id).exists():
			liked = True

	
	filtered_posts = PostFilter(
		request.GET,
		queryset=posts
	)
	
	post_paginator = Paginator(filtered_posts.qs, 3)
	page_num = request.GET.get('page')
	page = post_paginator.get_page(page_num)

	
	context = {
		'count' : post_paginator.count,
		'page' : page,
		'total_likes': total_likes,
		'liked': liked,
		'tag_list': tag_list
	}
	
	return render(request,'esko_app/profile.html', context)


def profileOther(request,username):
		
	post = get_object_or_404(Post,id=request.POST.get('post_id'))

	total_likes = post.total_likes()
	liked = False
	if post.likes.filter(id=request.user.id).exists():
		liked = True


	posts = Post.objects.filter(author=post.author).order_by('-date')
	print(posts)

	context = {
		'user' : post.author,
		'posts' :posts,
		'total_likes': total_likes,
		'liked': liked,
		'tag_list': post.tag_list(),
	}
	return render(request,'esko_app/other_profile.html', context)


def profileOtherComment(request,username):
	comment = get_object_or_404(Comment,id=request.POST.get('comment_id'))
	comments = Comment.objects.filter(commenter=comment.commenter)

	posts = Post.objects.filter(author=comment.commenter).order_by('-date')
	
	context = {
		'user' : comment.commenter,
		'posts' :posts,
		
	}	
	return render(request,'esko_app/other_profile_comment.html', context)




class PostDetailView(LoginRequiredMixin,DetailView):
	model = Post

	def get_context_data(self,*args, **kwargs):
		context = super(PostDetailView,self).get_context_data()

		# getting number of likes 
		get_post = get_object_or_404(Post, id=self.kwargs['pk'])
		total_likes = get_post.total_likes()
		tag_list = get_post.tag_list()

		liked = False
		if get_post.likes.filter(id=self.request.user.id).exists():
			liked = True

		context["total_likes"] = total_likes
		context["liked"] = liked
		context["tag_list"] = tag_list
		print(tag_list)
		print(get_post.tags)
		return context



class PostCreateView(LoginRequiredMixin,CreateView):
	model = Post
	form_class = CreatePostForm
	# fields = ['category','description','tags','post_image']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
	model = Post
	form_class = CreatePostForm
	# fields = ['category','description','tags','post_image']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super(PostUpdateView,self).form_valid(form)

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False

class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
	model = Post
	success_url = '/esko_app/profile'

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False


class ReportPostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
	model = Post
	success_url = '/esko_app/reported-posts'

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False


@login_required(login_url= '/esko_app/login/')
def LikeView(request,pk):
	post = get_object_or_404(Post,id=request.POST.get('post_id'))
	liked = False
	if post.likes.filter(id=request.user.id).exists():
		post.likes.remove(request.user)
		liked = False
	else:
		post.likes.add(request.user)
		liked = True


	return HttpResponseRedirect(reverse('esko_app:post-detail',args=[str(pk)]))



class AddCommentView(LoginRequiredMixin,CreateView):

templates/esko_app/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

		<div class="row px-5 pl-5 pt-1 pb-3" style="margin-top: 20px; width: 80%; margin-left: 170px">			
			<div class="row mx-auto py-2 ">
							
				<!--individual posts-->
				<div class="card py-3 px-4 " style="margin-bottom: 7px">
					<form method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						<legend class="border-bottom mb-4">Delete Post</legend>

						<h2>Are you sure you want to delete this post?</h2>

						<div class="card py-3  px-3 " style="margin-bottom: 7px;background: #323131" >
							<!--profile picture, username, category-->
								<div class="row px-3 py-1">
									<div class="col-auto px-0">
										<img src="{{ post.author.profile.profile_pic.url }}" class="rounded-circle" style="width:40px">
									</div>
									<div class="col-auto me-auto">
										<h5 class="card-title" style="color: white">{{ post.author }}</h5>
										<small  style="color:white">{{ post.date|date:"F d, Y" }}</small>
									</div>
									<div class="col-auto">
										<button type="button" class="btn btn-sm btn-secondary">{{ post.category }}</button>
										
									</div>
								</div>
							<!--content-->
							<div class="row px-4 py-1">
								<p class="card-text" style="margin-left: 30px">
								<a class="card-text" style="text-decoration: none;color:white" href="/esko_app/post/{{post.id}}">{{post.description}} </a></p>
								<!-- <img  src= "{{ post.image.url }}" style="width: 100%; margin-top: 60px"> -->
								{% for tag in post.tags.all   %}
										<a href="{% url 'esko_app:posts_by_tags' tag.slug %}" style="margin-left: 48px; margin-top: 10px; color:#ACB274; text-decoration: none ">#{{tag.name}}</a>
										{% endfor   %}
							</div>
						</div>
						
						<!--post submit button-->
						<div class="mb-3">
							<button class="btn btn-outline-danger" type="submit" >Delete</button>
							<a class="btn btn-outline-secondary" href="/esko_app/profile">Cancel</a>
						</div>
					</form>
				</div>
			</div>
		</div>
			

{% endblock content %}

templates/esko_app/post_detail.html
{% extends 'base.html' %}

{% block content %}
		<!-- <div class="container-fluid " style="background-color:#ECEEEE;"> -->
			<div class="row px-5 pl-5 pt-1 pb-3" style="margin-top: 20px; width: 80%; margin-left: 170px">
							
				<div class="row mx-auto py-2 ">
										
				<!--individual posts-->
				<div class="card py-3 px-4 " style="margin-bottom: 7px">
				<!--profile picture, username, category-->
					<div class="row px-3 py-1">
						<div class="col-auto px-0">
							<img src="{{ object.author.profile.profile_pic.url }}" class="rounded-circle" style="width:40px">
						</div>
						<div class="col-auto me-auto">
							<!-- <h5 class="card-title">{{ object.author }}</h5> -->
							<form action="{% url 'esko_app:profile-other' object.author %}" method="POST">
								{% csrf_token %}
								<button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-link" style="color:#515A5A;font-weight: bold;font-size: 20px; text-decoration: none">{{ object.author }}</button> 
							</form>
							<small class="text-muted" style="margin-left: 15px">{{ object.date|date:"F d, Y" }}</small>
						</div>
						<div class="col-auto">
							<button type="button" class="btn btn-sm btn-secondary">{{ object.category }}</button>
							<button type="button" class="btn btn-sm btn-light ms-2" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots"></i></button>
							<ul class="dropdown-menu" aria-labelledby="filterdropdownmenu">
							<li><button class="dropdown-item" type="button">
							<a class="dropdown-item" style="text-decoration: none;color: inherit;" href="#"><i class="bi bi-flag-fill">Report</i></a></button></li>
														
							<!-- if own post -->
							{% if object.author == user %}

							<li><button class="dropdown-item" type="button" >
							<a class="dropdown-item" style="text-decoration: none;color: inherit;" href="/esko_app/post/{{post.id}}/delete/">
							<i class="bi bi-trash-fill">Delete</i></a>
							</button></li>

							<li><button class="dropdown-item" type="button"><a class="dropdown-item" style="text-decoration: none;color: inherit;" href="/esko_app/post/{{post.id}}/update/"><i class="bi bi-pen-fill">Edit</i></a></button></li>
							{% endif %}

						</ul>
						</div>
					</div>
					<!--content-->
					<div class="row px-4 py-1">
						<p class="card-text" style="margin-left: 46px">{{object.description}}</p>

						{% if  post.post_image   %}
						<a href="{{ post.post_image.url }}">
							<img  src= "{{ post.post_image.url }}" style="width: 20%; height: 75%;margin-top: 12px; margin-left: 46px;margin-bottom: 5px">
						</a>
						{% endif   %}
					</div>

					<!-- tags, likes -->
					<div class="row px-3 py-1">
						<div class="col">
							<div class="container">
									<div class="col-md-8 mt-2 mb-2">
										<!-- {% for tag in post.tags.all   %} -->
										<!-- {% if post.tag_list   %} -->
										<!-- <a href="{% url 'esko_app:posts_by_tags' tag.slug %}" style="margin-left: 30px; margin-top: 10px; color:#ACB274; text-decoration: none "> -->
										<!-- #{{tag.name}}</a> -->
										<!-- {{post.tags}}</a> -->
										<!-- {% endif %} -->
										<!-- {% endfor %} -->
										<div class="btn-group" role="group">
										{% for tag in tag_list   %}
										<form class="d-flex" method=GET action="{% url 'esko_app:search_by_tags' %}">

											<button class="btn btn-link btn-sm" type="submit" name="search_box" value="{{tag}}" style="color: gray;font-size: 15px">#{{tag}}</button>
											
										</form>
										{% endfor   %}
										</div>
									</div>
								</div>
						</div>
								
						<div class="col-auto">
							<form action="{% url 'esko_app:like_post' post.pk %}" method="POST">
								{% csrf_token %}	

								{% if liked %}
									<button type="submit" name="post_id" value="{{ post.id }}" class="btn" style="background:white; font-size:1.1rem; color:#909911;"><i class="bi bi-heart-fill"></i></button>  
								{% else %}		
									<button type="submit" name="post_id" value="{{ post.id }}" class="btn" style="background:white; font-size:1.1rem; color:#909911;"><i class="bi bi-heart"></i></button> 
								{% endif %}	

								{% if post.total_likes == 1 %}
										{{ post.total_likes }} Like
								{% else %}
									{{ post.total_likes }} Likes
								{% endif %}
							</form>
						</div>
					</div>

					<hr style="width: 100%">

					<!--replies-->
					<div class="row px-3 py-1">
						<div class="col-auto me-auto">


							<h3>Comments...</h3>
							<br/>
							{% if not post.comments.all %}
								No comments Yet...
								<br/><br/>
								<a href="{% url 'esko_app:add_comment' post.pk %}" style="color:#909911 ">Add Comment</a>
								
								
							{% else %}
							<a href="{% url 'esko_app:add_comment' post.pk %}" style="color:#909911 ">Add Comment</a>
							<br/>

								{% for comment in post.comments.all %}
							

						<!--individual posts-->
								<div class="row px-3 py-1" style="margin-top: 15px">
									<div class="col-auto px-0">
										<img src="{{ comment.commenter.profile.profile_pic.url }}" class="rounded-circle" style="width:40px">
									</div>
									<div class="col-auto me-auto">
										<form action="{% url 'esko_app:profile-other-comment' comment.commenter %}" method="POST">
											{% csrf_token %}
											<button type="submit" name="comment_id" value="{{ comment.id }}" class="btn btn-link" style="color:#515A5A;font-weight: bold;font-size: 20px; text-decoration: none">{{ comment.commenter }}</button> 
										</form>
										<small class="text-muted" style="margin-left: 15px">{{ comment.date_added |date:"F d, Y" }}</small>
									</div>
									<div class="col-auto">
										
								
									</div>
							</div>
							
							<div class="row px-4 py-1">
								<p class="card-text" style="margin-left: 45px">
								<a class="card-text" style="text-decoration: none;color: inherit;" href="">{{ comment.body }} </a></p>
							</div>

								
									<br/>
								{% endfor %}
							{% endif %}
						</div>
						
					</div>
				</div>

			</div>
		</div>
								
								
	

{% endblock%}

templates/esko_app/sample_html.html
{% extends 'base.html' %}

{% block content %}
	<!-- code here -->
{% endblock %}

templates/esko_app/sell.html
{% extends 'base.html' %}

{% block content %}

		<div class="row px-5 pl-5 pt-1 pb-3" style="margin-top: 20px; width: 80%; margin-left: 170px">			
			
							
			<div class="row mx-auto py-2">
				
				<legend class=" mb-4">Post by Category</legend>
				
				{% for post in page %}
				<!--individual posts-->
				
						<!--individual posts-->
						<div class="card py-3 " style="margin-bottom: 7px" >
							<!--profile picture, username, category-->
								<div class="row px-3 py-1">
									<div class="col-auto px-0">
										<img src="{{ post.author.profile.profile_pic.url }}" class="rounded-circle" style="width:40px">
									</div>
									<div class="col-auto me-auto">
										<form action="{% url 'esko_app:profile-other' post.author %}" method="POST">
											{% csrf_token %}
											<button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-link" style="color:#515A5A;font-weight: bold;font-size: 20px; text-decoration: none">{{ post.author }}</button> 
										</form>
										<small class="text-muted" style="margin-left: 15px">{{ post.date|date:"F d, Y" }}</small>
									</div>
									<div class="col-auto">
										<button type="button" class="btn btn-sm btn-secondary">{{ post.category }}</button>
										<button type="button" class="btn btn-sm btn-light ms-2" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots"></i></button>
										<ul class="dropdown-menu" aria-labelledby="filterdropdownmenu">
											<li><button class="dropdown-item" type="button">
												
												<a class="dropdown-item" style="text-decoration: none;color: inherit;" href="#"><i class="bi bi-flag-fill">Report</i></a></button></li>
														
											<!-- if own post -->
											{% if post.author == user %}

											<li><button class="dropdown-item" type="button" >
												<a class="dropdown-item" style="text-decoration: none;color: inherit;" href="/esko_app/post/{{post.id}}/delete/">
													<i class="bi bi-trash-fill">Delete</i></a>
											</button></li>

											<li><button class="dropdown-item" type="button"><a class="dropdown-item" style="text-decoration: none;color: inherit;" href="/esko_app/post/{{post.id}}/update/"><i class="bi bi-pen-fill">Edit</i></a></button></li>
											{% endif %}

										</ul>
									</div>
								</div>
							<!--content-->
							<div class="row px-4 py-1">
								<p class="card-text" style="margin-left: 47px">
								<a class="card-text" style="text-decoration: none;color: inherit;" href="/esko_app/post/{{post.id}}">{{post.description}} </a></p>

								{% if  post.post_image   %}
								
								
								<a href="{{ post.post_image.url }}">
								<img  src= "{{ post.post_image.url }}" style="width: 20%; height: 75%;margin-top: 12px; margin-left: 25px;margin-bottom: 10px">
								</a>
								{% endif %}

								<div class="container">
									<div class="col-md-8 mt-2 mb-2">
										{% for tag in post.tags.all   %}
										<a href="{% url 'esko_app:posts_by_tags' tag.slug %}" style="margin-left: 48px; margin-top: 10px; color:#ACB274; text-decoration: none ">#{{tag.name}}</a>
										{% endfor   %}
									</div>
								</div>

							</div>
							
						
							<!--replies, likes-->
							<div class="row px-3 py-1">
								<div class="col-auto me-auto">
									<a class="btn" style="background:white; font-size:1.1rem; color:#909911" href="{% url 'esko_app:post-detail' post.pk %}"><i class="bi bi-reply-fill"></i>Replies</a>
								</div>
								<div class="col-auto">
								<form action="{% url 'esko_app:like_post' post.pk %}" method="POST">
								{% csrf_token %}	

								{% if liked %}
									<button type="submit" name="post_id" value="{{ post.id }}" class="btn" style="background:white; font-size:1.1rem; color:#909911;"><i class="bi bi-heart-fill"></i></button>  
								{% else %}		
									<button type="submit" name="post_id" value="{{ post.id }}" class="btn" style="background:white; font-size:1.1rem; color:#909911;"><i class="bi bi-heart"></i></button> 
								{% endif %}	

								{% if post.total_likes == 1 %}
										{{ post.total_likes }} Like
								{% else %}
									{{ post.total_likes }} Likes
								{% endif %}
							</form>
								</form>
								</div>
							</div>
						</div>
					{% endfor %}
			</div>
		</div>
			

{% endblock content %}