esko/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('esko_app/', include('esko_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path, include

from .views import (PostListView, PostDetailView,PostCreateView, PostUpdateView, 
	PostDeleteView, AddCommentView, HomeListView, PasswordsChangeView)

from . import views

from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'esko_app'
urlpatterns = [
	path('', views.index, name='index'),
	path('signup/', views.signup, name='signup'),
	path('login/', views.loginPage, name='login'),

	path('home/', views.home, name='home'),
	path('profile/', views.profile, name='profile'),


	# path('home/', HomeListView.as_view(), name='home'),
	# path('profile/', PostListView.as_view(), name='profile'),
	path('about/', views.about, name='about'),
	path('logout/', views.logoutUser, name='logout'),

	path('password-reset/', 
		PasswordsChangeView.as_view(template_name='esko_app/password_reset.html'),
		name= 'password_reset'),	
	path('password-reset/done/', views.password_success, name= 'password_success'),
	
	
	path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
	path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
	path('post/new/', PostCreateView.as_view(), name='post-create'),
	path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
	path('profileSettings/', views.profileSettings, name='profileSettings'),
	path('like/<int:pk>/',views.LikeView, name='like_post'),
	path('post/<int:pk>/comment', AddCommentView.as_view(), name='add_comment'),
	# path('post/<int:pk>/report', ReportView.as_view(), name='report'),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

		<!--Bootstrap icons-->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
		<!-- #DBCA46 -->
		<style type="text/css">
			.bgyellow{
				background: #DBCA46;
			}
			.col-form-label.req:after{
				content:'*'; 
				color:red;
			}
		
			.btn-link {
				color: white;
				font-size:30px;
			}
	
			.dropdown-menu li:hover ul.last {
				left: auto;
				right: 4px;
			}
	
		</style>

		<title>eSKO</title>
	</head>
	<body>
		<!-- Navigation bar -->
		<nav class="navbar navbar-expand-lg navbar-fixed navbar-dark bgyellow " style="overflow: visible;background-color: #DBCA46;position: sticky;top: 0;width: 100%;z-index: 1; ">
			<div class="container-fluid">
				<a class="navbar-brand" href="#">eSKO</a>
			</div>

			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-3 nav-fill">

					{% with url_name=request.resolver_match.url_name %}
						<li class="nav-item ">
						<a class="nav-link {% if url_name == 'home' %}active{% endif %}" href="/esko_app/home/">Home</a>
						</li>
						<li class="nav-item ">
						<a class="nav-link {% if url_name == 'categories' %}active{% endif %}" href="/esko_app/category/">Categories</a>
						</li>

						{% if request.user.is_superuser %}
						<li class="nav-item ">
						<a class="nav-link {% if url_name == 'reported-posts' %}active{% endif %}" href="/esko_app/reported-posts/">Reports</a>
						</li>
						{% endif %}

						<li class="nav-item ">
						<a class="nav-link {% if url_name == 'about' %}active{% endif %}" href="/esko_app/about/">About</a>
						</li> 
										
				</ul>

				<ul class="navbar-nav me-2 ms-3">
					{% if request.user.username != 'admin' %}
					<li class="nav-item me-1">
						<a class="btn btn-outline-light btn-sm text-nowrap mt-1" href="{% url 'esko_app:post-create' %}">Create Post</a>
					</li>
					{% endif %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle {% if url_name == 'profile' %}active{% endif %}"  id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							{{request.user}}
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="position: absolute;
				float: left;min-width: 100px;">
							<li><a class="dropdown-item" style="float: none;padding: 12px 16px;text-decoration: none;display: block;text-align: left;" href="/esko_app/profile/">Profile</a></li>
							<li><a class="dropdown-item" href="/esko_app/profileSettings/" style="float: none;padding: 12px 16px;text-decoration: none;display: block;text-align: left;" >Settings</a></li>
							<li><a class="dropdown-item" href="/esko_app/logout/" style="float: none;padding: 12px 16px;text-decoration: none;display: block;text-align: left;">Log Out</a></li>
						</ul>
					</li>
				</ul>
				{% endwith %}		
			</div>
		</nav>

		<!-- Create post modal-->
		<div class="modal" id="createPostModal">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						Create a new post
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">
						<form method="POST">
							{% csrf_token %}
							<!--category dropdown-->
							<div class="mb-3">
								<label for="postCategorySelection" class="col-form-label req">Category</label>
								<select class="form-select" id="postCategorySelection" required>
									<option selected disabled value="">--</option>
									<option value="sell">Sell</option>
									<option value="services">Services</option>
									<option value="swap">Swap</option>
									<option value="find">Find</option>
								</select>
							</div>
							<!--post description text box-->
							<div class="mb-3">
								<label for="postDescription" class="col-form-label req">Description</label>
								<textarea class="form-control" id="postDescription" placeholder="Enter listing's description here..."required></textarea>
							</div>
							<!--post tags text-->
							<div class="mb-3">
								<label for="postTags" class="col-form-label">Tags</label>
								<input type="text" class="form-control" id="postTags" placeholder="Enter post tags separated by commas...">
							</div>
							<!--post tags text-->
							<div class="mb-3">
								<label for="postImages" class="col-form-label">Images</label>
								<input type="file" class="form-control" id="postImages" multiple>
							</div>
							<!--required note-->
							<div class="mb-3">
								<p style="color:red">* Required</p>
							</div>
							<!--post submit button-->
							<div class="mb-3">
								<button class="btn bgyellow" type="submit" id="postSubmit">Post</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>





		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
		

		{% block content %}

		{% endblock %}

	</body>
</html>